# Numpy ---- Numerical Python

###### Data Science: is a branch of computer science where we study how to store, use and analyze data for deriving information from it.

In [3]:
import numpy as np

In [4]:
import pandas as pd

pd.DataFrame.fillna()

# I hope this is what you are talking about?

press tab to se the drop down menu


<img src='img01.jpg'>

##### Numpy is an important library for:

# Check Number of Dimensions?

In [1]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

#NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

#NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

print(a.ndim, a.shape, "---Zero dimesional")
print(b.ndim, b.shape , "---One dimesional")
print(c.ndim, c.shape , "---Two dimesional")
print(d.ndim, d.shape , "---Three dimesional")


0 () ---Zero dimesional
1 (5,) ---One dimesional
2 (2, 3) ---Two dimesional
3 (2, 2, 3) ---Three dimesional


# What is NumPy?
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by "Travis Oliphant". It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

# Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

Data Science: is a branch of computer science where we study how to store, use and analyze data for deriving information from it.

# convenience & speed

Numpy is much faster than the standard python ways to do computations.

Vectorised code typically does not contain explicit looping and indexing etc. (all of this happens behind the scenes, in precompiled C-code), and thus it is much more concise.

Also, many Numpy operations are implemented in C which is basically being executed behind the scenes, avoiding the general cost of loops in Python, pointer indirection and per-element dynamic type checking. The speed boost depends on which operations you're performing.

NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists

# Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

# NumPy Creating Arrays
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))#This built-in Python function tells us the type of the object passed to. 
# the above code shows that arr is numpy.ndarray type.

[1 2 3 4 5]
<class 'numpy.ndarray'>


#### To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray.

# Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

nested array: are arrays that have arrays as their elements.

# 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [4]:
#Create a 0-D array with value 42
import numpy as np
arr = np.array(42)
print(arr)

42


# 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

In [6]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


# 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [7]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [8]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


###### In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.


# Python Lists VS Numpy Arrays
1. Python stores data in several different ways like List, Dictionaries, Tuples, set, Numpy arrays etc.
Let's look how lists and arrays are similar and How they are different and what are the advantages of arrays over Lists.

# Similarities Between List and Numpy Array's
Both are used to store data
Both are mutable [i.e we can change the value in it at any point of time] 
Both can be indexed [i.e we can access the elements] and can iterate all elements persent in it.
can perform slicing operations upon them. [i.e we can get subset of elements from the whole data.]

# Differences Between List and Numpy Array's
1. List contain elements of different datatypes, whereas arrays contains elements of similar data type.
i.e we can store integer, float, string and all datatypes in a single list.

In [2]:
list1 = [1, 4.0, 'Apple']
print(list1)

[1, 4.0, 'Apple']


In [3]:
import numpy as np
arr1 = np.array([1, 2, 3, 4])
print(arr1)

[1 2 3 4]


### Type conversion take place if stored different datatypes

In [4]:
arr2 =np.array([1, 4.0, 'Apple'])
print(arr2)  #after converting to array every element of array has been converted to string. this is main disadvantage.

['1' '4.0' 'Apple']


In [8]:
print(type(arr2[0]))

<class 'numpy.str_'>


In [9]:
type(arr2[1])

numpy.str_

In [10]:
type(arr2[2])

numpy.str_

#### 2. Way of performing operations

In [11]:
arr = np.array([5, 10, 15, 20])
print(arr)
print(type(arr))

[ 5 10 15 20]
<class 'numpy.ndarray'>


In [12]:
arr/5

array([1., 2., 3., 4.])

In [13]:
list1 = [5, 10, 15, 20]
print(list1)

[5, 10, 15, 20]


In [14]:
list1/5

TypeError: unsupported operand type(s) for /: 'list' and 'int'

# 3. Installation
.To use numpy arrays we need to install and import numpy library, whereas List is Buit_in and we no need to install anything and we can directly use it.

# Advantages of array over List
.Numpy array consume less memory.
.Numpy array are faster than Lists.

# Numpy Array Reshaping

Importing Numpy

# Creating sample numpy array

In [28]:
import numpy as np
a = np.arange(12)
print(a)
print(type(a))
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
1


# Reshaping into two dimensional array

In [35]:
new_a = a.reshape(2,6)
print(new_a)
print(new_a.ndim)
print(new_a.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
2
(2, 6)


# Let's convert 2-D array to 1-D array

In [30]:
b = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B =  np.array(b)
print(B)
print(B.ndim)
print(B.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [31]:
new_B = B.reshape(9)
print(new_B)
print(new_B.ndim)
print(new_B.shape)

[1 2 3 4 5 6 7 8 9]
1
(9,)


# Additional Tips

1. Make sure that we will always provide right dimensions such that number of elements are same before and after reshaping.

2. If we don't know the exact dimensions for conversions, use -1 so that numpy will figure it out the correct dimensions.

Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.

In [36]:
b = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
B = np.array(b)
print(B)
print(B.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [37]:
new_B = B.reshape(4, -1)
print(new_B)
print(new_B.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


# Numpy Array Indexing
Note:
1. Similar to List, we can access the array using index
2. can retrieve single value of an array
3. Zero based Indexing
4. Negative Indexing also possible

In [38]:
a = [1, 2, 3, 4]
A = np.array(a)
print(a)
print(A.shape)

[1, 2, 3, 4]
(4,)


In [39]:
print(a[3])
print(a[-1])

4
4


In [40]:
print(a[1])
print(a[-3])

2
2


# Accessing Two_dimensional array
Note: (i, j)
1. 'i' respects to rows and 'j' respects to column.

In [41]:
b = [[1, 2], [3, 4]]
B = np.array(b)
print(B)
print(B.shape)

[[1 2]
 [3 4]]
(2, 2)


In [42]:
print(B[0][0])
print(B[-2][-2])
print(B[-1][-2])
print(B[1][0])

1
1
3
3


# Accessing Three_Dimensional Array

In [43]:
c = [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]
c = np.array(c)
print(c)
print(c.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
(2, 3, 3)


In [31]:
print(c[0][0][2])
print(c[-2][-3][-1])

3
3


In [32]:
print(c[1][2][2])
print(c[-1][-1][-1])

18
18


# Slicing Operation

In [3]:
import numpy as np

# Accessing one Dimensional Array

one diemensional array

In [44]:
a = [1, 4, 7, 11, 6, 3]
A = np.array(a)
print(A)
print(type(A))

[ 1  4  7 11  6  3]
<class 'numpy.ndarray'>


In [45]:
print(A[0:3:1])

[1 4 7]


In [46]:
print(A[0:3:2])

[1 7]


## Task3: let's take the first 3 elements

In [8]:
print(A[:3]) # here i am not mentioning the start index value, but default value is 0.

[1 4 7]


Task4: let's get all the elements from 2nd index upto the last

In [12]:
print(A[2:]) #here, I have not mentioned the last index butimplicitly taken care

[ 7 11  6  3]


Task5: let's print the elements with step size 2.

In [14]:
print(A[::2]) #here the start and end index has been implicitly taken care by numpy. 

[1 7 6]


# Note:
To get all element, use this format 

In [15]:
print(A[::])

[ 1  4  7 11  6  3]


# Two Dimensional Array

In [124]:
b = [[4, 7, 11], [6, 13, 9], [2, 12, 100]]
B = np.array(b)
print(B)
print(type(B))
print(B.shape)


[[  4   7  11]
 [  6  13   9]
 [  2  12 100]]
<class 'numpy.ndarray'>
(3, 3)


###### Task1: Let's get all elements 9 and 100.

In [17]:
print(B)

[[  4   7  11]
 [  6  13   9]
 [  2  12 100]]


In [18]:
print(B[1:3:1, 2:3:1])

[[  9]
 [100]]


###### Task2: Let#s get the sun matrix [[6 13], [2 12]]

In [19]:
print(B[1:3:1, 0:2:1])

[[ 6 13]
 [ 2 12]]


###### Task3: Let's print the entire matrix

In [22]:
print(B[:,:])   # doubt

[[  4   7  11]
 [  6  13   9]
 [  2  12 100]]


# Three Dimensional Arrays

In [23]:
c = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
C = np.array(c)
print(C)
print(C.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


###### Task1: Let's slice each and every element in 3-D Array

In [24]:
C[: ,: , :]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

###### Task2: Let's slice only first(1) matrix in 3-D array 

In [26]:
C[0:1, :, :]   #Here 1 is exclusive that means, it will not include the 1th index matxix.

array([[[1, 2, 3],
        [4, 5, 6]]])

###### Task3: Let#s get the 0th column in all matrix

In [28]:
C[: , : , 0:1]

array([[[ 1],
        [ 4]],

       [[ 7],
        [10]]])

# View Vs. Copy in Numpy

importing Numpy package

In [47]:
import numpy as np

###### Let's understand the functionality of view()

In [27]:
arr1 = np.array([10, 20, 30 ,40])
print(arr1)

[10 20 30 40]


In [28]:
arr2 = arr1.view()
arr2[1]= 1000

In [29]:
print(arr2)

[  10 1000   30   40]


In [30]:
print(arr1)  #Here we can clearly see that changes made in arr2 got reflected in arr1.

[  10 1000   30   40]


In [31]:
#Check memory share between arr1 and arr2
np.shares_memory(arr1, arr2)

True

###### Let#s understand the functionality of copy.

In [23]:
arr1 = np.array([10, 20, 30, 40])
print(arr1)

[10 20 30 40]


In [24]:
arr2 = arr1.copy()
arr2[1] = 1000
print(arr2)

[  10 1000   30   40]


In [25]:
#Check memory share between arr1 and arr2
np.shares_memory(arr1, arr2)

False

In [26]:
print(arr1) #' we can crealy see that changes made in arr2 not at all reflected in arr1'
            # This show that by using "copy()" we can completly owns the data.

[10 20 30 40]


In [33]:
# Check if every element in array a greater than 3 or not Using '>' notation
arr1 > 3

array([ True,  True,  True,  True])

In [34]:
# check if each elements in array 'arr1' equals array 'arr2' using '==' notation
arr1==arr2

array([ True,  True,  True,  True])

# The Difference Between Copy and View

# Check if Array Owns its Data

In [2]:
#Print the value of the base attribute to check if an array owns it's data or not:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


# Joining Arrays Using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [56]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


# Hstack Vs Vstack

Note:
    1. Hstack is used to join two arrays Horizontally.
    2. Vstack is used to join two arrays Vertically.

In [58]:
import numpy as np

###### Performing Hstack  : Stacking Along Rows

In [63]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a: {}".format(a))
print("Dimension of a:", a.ndim)

print("b: {}".format(b))
print("Dimension of b:", b.ndim)

a: [1 2 3]
Dimension of a: 1
b: [4 5 6]
Dimension of b: 1


In [64]:
c = np.hstack((a,b))
print("c: {}".format(c))
print("Dimension of c:", c.ndim)

c: [1 2 3 4 5 6]
Dimension of c: 1


###### Performing Vstack  : Stacking Along Columns

In [61]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a: {}".format(a))
print("Dimension of a:", a.ndim)

print("b: {}".format(b))
print("Dimension of b:", b.ndim)

a: [1 2 3]
Dimension of a: 1
b: [4 5 6]
Dimension of b: 1


In [62]:
c = np.vstack((a,b))
print("c: {}".format(c))
print("Dimension of c:", c.ndim)

c: [[1 2 3]
 [4 5 6]]
Dimension of c: 2


# Stacking Along Height (depth)

NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [67]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
arr = np.dstack((arr1, arr2, arr3))

print(arr)

[[[1 4 7]
  [2 5 8]
  [3 6 9]]]


# Numpy Concatenation

In [68]:
import numpy as np

##### Creating Numpy array

In [3]:
a = [[1, 2], [4, 5]]
A = np.array(a)
print(A)
print(A.shape)

[[1 2]
 [4 5]]
(2, 2)


In [4]:
b = [[7], [8]]
B = np.array(b)
print(B)
print(B.shape)

[[7]
 [8]]
(2, 1)


In [5]:
c = [[9, 10]]
C = np.array(c)
print(C)
print(C.shape)

[[ 9 10]]
(1, 2)


#### Note:
    1. When axis = 0, Both concatenating arrays should have the same numbers of columns.[Think            like adding a new row]
    
    2. When axis = 1, Both concatenating arrays should have the same number of rows.(Think like          adding a new column]

In [6]:
print(A.shape)

(2, 2)


In [7]:
print(C.shape)

(1, 2)


In [8]:
D = np.concatenate((A, C), axis = 0)
print(D)
print(D.shape)   #Observation: Works similar to np.vstack()

[[ 1  2]
 [ 4  5]
 [ 9 10]]
(3, 2)


In [9]:
print(A.shape)

(2, 2)


In [10]:
print(B.shape)

(2, 1)


In [11]:
E = np.concatenate((A, B), axis = 1)
print(E)
print(E.shape)   #Observation: Works similar to np.vstack()

[[1 2 7]
 [4 5 8]]
(2, 3)


# Finally

Note: When you tried to add arrays of different rows with axis = 1 we will get error.

#### Different columns:

In [12]:
print(A.shape)
print(C.shape)

(2, 2)
(1, 2)


In [13]:
F = np.concatenate((A, c), axis = 1)
print(F)
print(F.shape)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [81]:
print(A.shape)
print(B.shape)

(2, 2)
(2, 1)


In [83]:
G = np.concatenate((A, B), axis = 0)
print(G)
print(G.shape)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

# Insert, Append and Delete Numpy Array

## Appending

In [14]:
#Let's create new array
a = [1, 2, 3, 4, 5]
arr = np.array(a)
print(arr)

[1 2 3 4 5]


In [15]:
np.append(arr, 45)

array([ 1,  2,  3,  4,  5, 45])

In [16]:
#While appending multiple values, make sure that you pass through the list only
np.append(arr, [100, 150,80])

array([  1,   2,   3,   4,   5, 100, 150,  80])

In [17]:
#'priting the original array'
print(arr)

[1 2 3 4 5]


In [18]:
b = np.append(arr, 45)
print(b)

[ 1  2  3  4  5 45]


In [19]:
b = np.append(b, [100, 150, 180])
print(b)

[  1   2   3   4   5  45 100 150 180]


# Insertion in 2-Dimensional Array

In [20]:
b = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr2 = np.array(b)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Adding new row to matrix 

###### Need to mention axis = 0 for appending to the new rows

In [21]:
arr3 = np.append(arr2, [[10, 11, 12]], axis = 0)
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### Adding new column to matrix

###### Need to mention axis = 1 for appending to the new columns

In [22]:
arr4 = np.append(arr2, [[10], [11], [12]], axis = 1)

print(arr4)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


# Inserting Elements into Array

In [23]:
A = np.array([1, 2, 3, 4, 5])
print(A)

[1 2 3 4 5]


#### Inserting -100 at first position of numpy array

In [24]:
np.insert(A, 1, -100)

array([   1, -100,    2,    3,    4,    5])

In [25]:
b = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B = np.array(b)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


###### Inserting new Row at the first position of numpy matrix.

In [26]:
np.insert(B, 1, [120, 140, 80], axis = 0)

array([[  1,   2,   3],
       [120, 140,  80],
       [  4,   5,   6],
       [  7,   8,   9]])

###### Inserting new column at the first position of numpy matrix.

In [27]:
np.insert(B, 1, [12, 14, 180], axis = 1)

array([[  1,  12,   2,   3],
       [  4,  14,   5,   6],
       [  7, 180,   8,   9]])

# Deletion

###### One Dimensional array

In [28]:
A = np.array([1, 2, 3, 4, 5])
print(A)

[1 2 3 4 5]


###### Let's delete the element which is presend at 2nd index

In [29]:
np.delete(A, 2)

array([1, 2, 4, 5])

In [30]:
b = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B = np.array(b)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
np.delete(b, 1, axis = 0)

array([[1, 2, 3],
       [7, 8, 9]])

In [32]:
np.delete(b, 1, axis = 1)

array([[1, 3],
       [4, 6],
       [7, 9]])

# Lopping over array and stacking/splitting of arrays

In [33]:
import numpy as np

In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr: #x denotes the every list as a songle item
    for y in x:  #denotes the each elements of each item or list or x.
        print(y)

1
2
3
4
5
6


In [36]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [37]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:   #here x denotes the each two dimensional array
    for y in x:   #here y denote the each one dimensional array
        for z in y:  #here z denotes the each elements of list members
           
            print(z)



1
2
3
4
5
6
7
8
9
10
11
12


# Transpose:
    

In [38]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

print('arr1 before transpose: \n', arr1)
print(arr1.shape)
print(arr1.ndim)
print('arr1 after transpose: \n', arr1.T)
print(arr.T.shape)   
print(arr.T.ndim)
#before transpose: (2, 3) ---> (3, 2)

arr1 before transpose: 
 [[1 2 3]
 [4 5 6]]
(2, 3)
2
arr1 after transpose: 
 [[1 4]
 [2 5]
 [3 6]]
(3, 2, 2)
3


In [39]:
arr1 = np.array([1, 2, 3], ndmin=2)
print(arr1)
arr2 = np.array([4, 5, 6], ndmin=2)

arr = np.concatenate((arr1, arr2))
print('---------------')
print(arr)

[[1 2 3]]
---------------
[[1 2 3]
 [4 5 6]]


In [40]:
arr1 = np.array([1, 2, 3], ndmin=2)

arr2 = np.array([4, 5, 6], ndmin=2)

arr = np.concatenate((arr1, arr2), axis = 1)

print(arr)

[[1 2 3 4 5 6]]


In [41]:
arr1 = np.array([1, 2, 3], ndmin=2)

arr2 = np.array([4, 5, 6], ndmin=2)

arr = np.concatenate((arr1, arr2), axis = 0)

print(arr)

[[1 2 3]
 [4 5 6]]


In [42]:
arr1 = np.array([[1, 2], [3, 4]])
print('arr1 before concat: \n', arr1)
arr2 = np.array([[4, 5], [6, 7]])
print('arr2 before concat: \n', arr2)

arr= np.concatenate((arr1, arr2), axis =1)

print('after contact along axis=1 \n', arr)



arr1 before concat: 
 [[1 2]
 [3 4]]
arr2 before concat: 
 [[4 5]
 [6 7]]
after contact along axis=1 
 [[1 2 4 5]
 [3 4 6 7]]


In [43]:
arr1 = np.array([[1, 2], [3, 4]])
print('arr1 before concat: \n', arr1)
arr2 = np.array([[4, 5], [6, 7]])
print('arr2 before concat: \n', arr2)

arr= np.concatenate((arr1, arr2), axis =0)

print('after contact along axis=0 \n', arr)

print(arr.shape)

arr1 before concat: 
 [[1 2]
 [3 4]]
arr2 before concat: 
 [[4 5]
 [6 7]]
after contact along axis=0 
 [[1 2]
 [3 4]
 [4 5]
 [6 7]]
(4, 2)


In [44]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis = 1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [45]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis = 0)

print(arr)

[[1 2 3]
 [4 5 6]]


In [46]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [47]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [149]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 4)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [26]:
#Note
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [150]:
x = np.arange(8.0)
print('x before split ', x)
np.array_split(x,3)

x before split  [0. 1. 2. 3. 4. 5. 6. 7.]


[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr= np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [151]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr= np.array_split(arr, 3, axis=0)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


# Some other Operations of numpy (np.random, np.dot, np.add etc)

In [154]:
arr = np.array([1,2,3,4,5,4, 4])
x = np.where(arr == 4)
print(x)


(array([3, 5, 6], dtype=int64),)


In [155]:
arr = np.array([1,2,3,4,5,4, 4])
x = np.where(arr == 5)
print(x)

(array([4], dtype=int64),)


# Converting dtype in  an array

In [156]:
arr = np.array([1, 0, 4, 0, 3, 7])
print('arr before convert ', arr)
print(arr.dtype)
arr = arr.astype(bool)
print('arr after convert ', arr)
print(arr.dtype)


arr before convert  [1 0 4 0 3 7]
int32
arr after convert  [ True False  True False  True  True]
bool


In [157]:
x = np.random.randint(100, size = (5))
print(x)

[48 76 40 32 60]


In [158]:
x = np.random.randint(100, size = (3, 5))
print(x)

[[13 18 88 76 33]
 [71 98 45 86 57]
 [90  2 30 10 22]]


In [159]:
x = np.random.choice([3, 5, 7 , 9])
print(x)

3


In [160]:
x = np.random.choice([3, 5, 7 , 9, 1, 0], size = (3, 5))
print(x)

[[0 0 5 5 3]
 [0 0 7 7 0]
 [3 5 3 9 3]]


In [161]:
x = np.random.choice([3, 5, 7 , 9], p = [0.1, 0.3, 0.6, 0.0], size = 100)
print(x)

[7 7 5 5 7 7 7 7 7 7 7 7 5 5 7 5 5 7 7 5 3 5 5 7 5 7 7 3 7 7 5 5 7 7 5 7 7
 5 7 7 5 7 5 5 7 3 7 5 7 7 5 7 7 7 5 7 7 3 5 7 7 7 7 5 7 7 7 5 7 5 7 7 5 7
 7 3 3 7 7 7 7 7 7 3 3 5 7 5 7 5 3 7 7 7 7 7 7 7 5 7]


In [48]:
x = np.random.normal(size=(2, 3))
print(x)

[[-0.29945283 -0.15021542  0.61099841]
 [ 1.57132126  0.74508823  0.61670338]]


In [50]:
x = np.random.normal(loc=1, scale=2, size=(2, 3))
print(x)

[[ 2.38989458  0.04464154  1.11340984]
 [ 4.02678153  2.16056826 -0.67508816]]


In [162]:
# Printing all numbers from 1 to 
# 2 in steps of 0.1
print(np.arange(1, 2, 0.1))


[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [174]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [163]:
import numpy as np
print(np.zeros([2, 2]))

[[0. 0.]
 [0. 0.]]


In [164]:
print(np.ones([2, 2]))

[[1. 1.]
 [1. 1.]]


In [4]:
a= np.arange(20).reshape(5,2,2)
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [27]:
a= np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [167]:
a= np.arange(20).reshape(5,2,2)
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [5]:
a= np.arange(20).reshape(4,5,-1)
print(a)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]]

 [[15]
  [16]
  [17]
  [18]
  [19]]]


In [169]:
a = [[1, 0], [0,1]]
print(a)
b = [[4, 1], [2, 2]]
print(b)

print('-----------------')
np.dot(a, b)
print(np.dot(a, b).shape)

[[1, 0], [0, 1]]
[[4, 1], [2, 2]]
-----------------
(2, 2)


In [175]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

In [170]:
a = [[1, 0], [0,1]]
b = [[4, 1], [2, 2]]
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

In [176]:
help(np.matmul)

Help on ufunc:

matmul = <ufunc 'matmul'>
    matmul(x1, x2, /, out=None, *, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj, axes, axis])
    
    Matrix product of two arrays.
    
    Parameters
    ----------
    x1, x2 : array_like
        Input arrays, scalars not allowed.
    out : ndarray, optional
        A location into which the result is stored. If provided, it must have
        a shape that matches the signature `(n,k),(k,m)->(n,m)`. If not
        provided or None, a freshly-allocated array is returned.
    **kwargs
        For other keyword-only arguments, see the
        :ref:`ufunc docs <ufuncs.kwargs>`.
    
        .. versionadded:: 1.16
           Now handles ufunc kwargs
    
    Returns
    -------
    y : ndarray
        The matrix product of the inputs.
        This is a scalar only when both x1, x2 are 1-d vectors.
    
    Raises
    ------
    ValueError
        If the last dimension of `x1` is not the same size as
        the secon

In [1]:
import numpy as np 
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [4]:
np.full((2, 2), 10)


array([[10, 10],
       [10, 10]])

In [9]:
x = np.arange(9).reshape((3,3))
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
print(np.diag(x))

[0 4 8]


In [11]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [12]:
#create a numpy array using diag function passing a list [1,2,3,4,5]
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [177]:
import numpy.matlib 
import numpy as np 

a = [[1,0],[0,1]] 
b = [1,2] 
print(np.matmul(a,b)) 
print(np.matmul(b,a))

[1 2]
[1 2]


In [13]:
# Create a numpy array v with [1,2,3] as its elements
v = np.array([1,2,3])


#Use tile function of numpy and pass v and (3,1) as its parametrs
np.tile(v,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [14]:
b = np.array([[1, 2], [3, 4]])
np.tile(b, 2)


array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [19]:
np.tile(b, (2, 5)) #five times repetition of columns as it is 5
#twice repetition of rows as it is 2.

array([[[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]],

       [[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]]])

In [20]:
# Create an array with 100 values between 1 and 50 using linspace
np.linspace(1, 50, 100)

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [21]:
np.random.random((3,3))

array([[0.98642244, 0.87107484, 0.5823207 ],
       [0.44020268, 0.25657427, 0.96805817],
       [0.02951696, 0.43372013, 0.22911349]])

In [22]:
# Flattening y
x=np.arange(1,17)
y = x.reshape(2,4,-1)
y.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [178]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20

In [179]:
a = np.ones([9, 5, 7, 4])
print(a)
print(a.shape)

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]


In [31]:
a = np.ones([9, 5, 7, 4])
c = np.ones([9, 5, 4, 3])


np.dot(a, c).shape
#(9, 5, 7, 9, 5, 3)  
np.matmul(a, c).shape
#(9, 5, 7, 3)

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]


(9, 5, 7, 3)

In [8]:
a = [[1, 0], [0,1]]   # https://www.mathsisfun.com/algebra/matrix-multiplying.html
b = [[4, 1], [2, 2]]  # matrix multiplication
np.multiply(a, b)

array([[4, 0],
       [0, 2]])

In [186]:
import numpy as np 
a = np.array([99, 98, 97, 96, 95])
print('a:', a ,'\n')
b = np.arange(20).reshape(5, 4)
print('b:', b,'\n')
c = np.arange(5).reshape(1, 5).T
print('c:', c,'\n')
d = np.hstack((b, c))#number of rows should be same
print('d:',d,'\n')
print(np.vstack((d, a))) #number of column should be same

a: [99 98 97 96 95] 

b: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

c: [[0]
 [1]
 [2]
 [3]
 [4]] 

d: [[ 0  1  2  3  0]
 [ 4  5  6  7  1]
 [ 8  9 10 11  2]
 [12 13 14 15  3]
 [16 17 18 19  4]] 

[[ 0  1  2  3  0]
 [ 4  5  6  7  1]
 [ 8  9 10 11  2]
 [12 13 14 15  3]
 [16 17 18 19  4]
 [99 98 97 96 95]]


In [185]:
c = np.arange(5)
c


array([0, 1, 2, 3, 4])

# Assert:

Python Provides the assert statement to check if a given logical expression is true or false. Program execution procceds only if the expression is true and raises the assertionError when it is false. The following code shows the usage of the assert statement.

In [1]:
#Example
num = 10
assert num > 10 #false condition

AssertionError: 

In [4]:
num = 10
assert num >= 10 #executed fine----no error raised

In [193]:
import numpy as np
x = np.arange(-5, 4).reshape(3, 3)
print(x)
print(x.shape[1])
def navie_relu(x):
    assert len(x.shape) == 2
   
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
              x[i, j] = max(x[i, j], 0)
    return x        
print(navie_relu(x))

[[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]
3
[[0 0 0]
 [0 0 0]
 [1 2 3]]


In [198]:
x=max(1, 7)
x

7

In [4]:
x = np.arange(-5, 4).reshape(3, 3)

print(x)

print(x.shape)

[[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]
(3, 3)


In [211]:
x = np.arange(-5,4).reshape(3,3)
y = np.arange(0,9).reshape(3,3)

print('x:', x)
print('y:', y)
print('shape of x:', x.shape)
print('shape of y:', y.shape)
print(len(x.shape))
print(len(y.shape))
def guess_what_function(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
              x[i, j] += y[i, j]
    return x        
print(guess_what_function(x, y))

x: [[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]
y: [[0 1 2]
 [3 4 5]
 [6 7 8]]
shape of x: (3, 3)
shape of y: (3, 3)
2
2
[[-5 -3 -1]
 [ 1  3  5]
 [ 7  9 11]]


In [202]:
x = np.arange(-5,4).reshape(3,3)
y = np.arange(0,9).reshape(3,3)
print(x)
print(y)

[[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [209]:
a = np.arange(-5, 4).reshape(3, 3)
b = np.array([1,2, 3 ])
print(len(a.shape))
print(len(b.shape)) 
def guess_what(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
              x[i, j] += y[j] 
    return x        
print(guess_what(a,b))

2
1
[[-4 -2  0]
 [-1  1  3]
 [ 2  4  6]]


In [212]:
def guess_what(x,y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    z = 0
    for i in range(x.shape[0]):
        z += x[i] *y[i]
    return z

c = np.array([3, 4, 5])
d = np.array([1, 2, 3])
print(guess_what(c, d))
print(len(c.shape))


26
1


In [13]:
c = np.array([3, 4, 5])
print(len(c.shape))

1


In [225]:
def guess_what(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]
    z = np.zeros(x.shape[0])
    print('z:',z)
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i, j]*y[j]
    return z
c = np.arange(9).reshape(3, 3)
d = np.arange(3).reshape(3, 1)
print('c:', c)
print('len of c:',len(c.shape))
print('shape of c',c.shape[1])
print('d:', d)
print('len of d:',len(d.shape))
print('shape of d',d.shape[0])
print(guess_what(c, d))


c: [[0 1 2]
 [3 4 5]
 [6 7 8]]
len of c: 2
shape of c 3
d: [[0]
 [1]
 [2]]
len of d: 2
shape of d 3
z: [0. 0. 0.]
[ 5. 14. 23.]


In [31]:
import pandas as pd
import numpy as np
 
df1 = pd.DataFrame(np.random.randint(25, size=(4, 4)),
                   index=["1", "2", "3", "4"],
                   columns=["A", "B", "C", "D"])
 
df2 = pd.DataFrame(np.random.randint(25, size=(6, 4)),
                   index=["5", "6", "7", "8", "9", "10"],
                   columns=["A", "B", "C", "D"])
 
df3 = pd.DataFrame(np.random.randint(25, size=(4, 4)),
                   columns=["A", "B", "C", "D"])
 
df4 = pd.DataFrame(np.random.randint(25, size=(4, 4)),
                   columns=["E", "F", "G", "H"])
 
display('df1:',df1, 'df2:', df2, 'df3:',df3, 'df4:',df4,)

'df1:'

A   B   C   D
1  20   9  19  18
2   4  15   4  13
3   3  17   5  17
4   7  15  24   1

'df2:'

A   B   C   D
5    8   8  15   8
6   16  17  11  15
7    2   4  18   3
8   15  21  20  15
9   22  11  14   4
10   4   5  20  18

'df3:'

A   B   C   D
0  20  21   7  24
1  14  12   0   5
2  13   1  23   1
3  16   0   4   1

'df4:'

E   F   G   H
0   9   0   0  24
1  24  22   6   3
2  20   9  22  24
3   6  17  13   7